let data,deferredPrompt=null,currentView='today',quotes=[],quoteIndex=0,reminderTimers=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const todayKey=()=>new Date().toISOString().slice(0,10);
const day=()=>data.days[todayKey()] ||= {steps:0,calories:0,protein:0};
const fmt=n=>Number(n||0).toLocaleString('fr-FR');
async function save(render=true){await DB.save(data);if(render)renderAll()}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}
function weekStart(d=new Date()){const x=new Date(d);const wd=(x.getDay()+6)%7;x.setDate(x.getDate()-wd);return x.toISOString().slice(0,10)}
function calcStreak(){let n=0,d=new Date();for(;;){const k=d.toISOString().slice(0,10),has=(data.days[k]?.steps>0)||data.workouts.some(w=>w.date===k&&w.completed);if(!has)break;n++;d.setDate(d.getDate()-1)}return n}
function weekWorkoutCount(){const start=weekStart();return data.workouts.filter(w=>w.completed&&w.date>=start&&!w.minimum).length}
function latestReview(){return [...data.weeklyReviews].at(-1)||Engine.review(data)}
function renderAll(){renderToday();renderWorkout();renderProgress();renderSettings();renderStoriesStrip();renderStories();scheduleSmartReminders()}
function renderToday(){const w=[...data.weights].sort((a,b)=>a.date.localeCompare(b.date)),latest=w.at(-1),delta=Engine.weeklyDelta(w),d=day();$('#weightNow').textContent=latest?Number(latest.value).toFixed(1):'—';$('#trendText').textContent=delta==null?'Il faut deux semaines de pesées régulières pour la tendance.':`${delta<=0?'↓':'↑'} ${Math.abs(delta).toFixed(1)} kg entre les moyennes hebdomadaires`;$('#stepsNow').textContent=fmt(d.steps);$('#stepsTarget').textContent=`/ ${fmt(data.profile.stepsTarget)}`;$('#streakNow').textContent=calcStreak();$('#weekWorkouts').textContent=weekWorkoutCount();$('#calText').textContent=`${fmt(d.calories)} / ${fmt(data.profile.calTarget)}`;$('#proteinText').textContent=`${fmt(d.protein)} / ${fmt(data.profile.proteinTarget)} g`;$('#calBar').style.width=`${Math.min(100,(d.calories||0)/data.profile.calTarget*100)}%`;$('#proteinBar').style.width=`${Math.min(100,(d.protein||0)/data.profile.proteinTarget*100)}%`;const r=latestReview();$('#autopilotHeadline').textContent=r.title||'Autopilot';$('#autopilotText').textContent=r.text||'';$('#autopilotBadge').textContent=r.eligible===false?'Données':r.action==='hold'?'Stable':'Ajusté'}
function renderWorkout(){const plan=Engine.todaysPlan(data),sets=Engine.setCount(data);$('#workoutTitle').textContent=`Workout ${plan}`;$('#workoutDuration').textContent=sets===2?'~25 min':'~30 min';$('#exerciseList').innerHTML=Engine.plans[plan].map(ex=>{const p=Engine.prescription(data,ex);return `<div class="exercise"><b>${ex.name}</b><span>${p.text}${p.load!==''&&p.load!=null?` • ${p.load} kg`:''}</span></div>`}).join('');$('#nextProgression').innerHTML=Engine.plans[plan].filter(x=>x.type==='strength').slice(0,4).map(ex=>{const p=Engine.prescription(data,ex);return `<div class="history-row"><span>${ex.name}</span><small>${p.load||'—'} kg · ${p.text}</small></div>`}).join('');$('#workoutHistory').innerHTML=[...data.workouts].reverse().slice(0,6).map(w=>`<div class="history-row"><span>${w.date} · ${w.minimum?'Minimum':`Workout ${w.plan}`}</span><small>${w.minimum?'habit':`${Math.round(Engine.volume(w))} kg·rep`}</small></div>`).join('')||'<p class="subtle">Aucune séance enregistrée.</p>'}
function drawLine(canvas,points,labelFn){const ctx=canvas.getContext('2d'),w=canvas.clientWidth||320,h=180,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,h*i/4);ctx.lineTo(w,h*i/4);ctx.stroke()}if(points.length<2){ctx.fillStyle='#64748b';ctx.font='13px system-ui';ctx.fillText('Pas assez de données',12,24);return}const vals=points.map(p=>p.v),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;ctx.strokeStyle='#0b1020';ctx.lineWidth=3;ctx.beginPath();points.forEach((p,i)=>{const x=i*(w-20)/(points.length-1)+10,y=h-20-((p.v-min)/range)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#64748b';ctx.font='11px system-ui';ctx.fillText(labelFn(min),6,h-4);ctx.fillText(labelFn(max),w-48,12)}
function renderProgress(){const weights=[...data.weights].sort((a,b)=>a.date.localeCompare(b.date)).slice(-30).map(x=>({v:Number(x.value),d:x.date}));drawLine($('#weightChart'),weights,v=>`${v.toFixed(1)} kg`);const vols=data.workouts.filter(w=>w.completed&&!w.minimum).slice(-8).map(w=>({v:Engine.volume(w),d:w.date}));drawLine($('#volumeChart'),vols,v=>`${Math.round(v)}`);$('#reviewHistory').innerHTML=[...data.weeklyReviews].reverse().slice(0,8).map(r=>`<div><div class="history-row"><b>${r.week}</b><small>${r.rate!=null?r.rate.toFixed(2)+'%/sem':''}</small></div><div class="subtle">${r.text}</div></div>`).join('')||'<p class="subtle">Aucune revue appliquée pour le moment.</p>'}
function renderSettings(){for(const [id,key] of [['calTarget','calTarget'],['proteinTarget','proteinTarget'],['stepsTargetInput','stepsTarget'],['minCalTarget','minCalTarget'],['loadIncrement','loadIncrement']])$('#'+id).value=data.profile[key];$('#autopilotEnabled').checked=!!data.profile.autopilotEnabled;$('#notifyStatus').textContent=('Notification'in window)&&Notification.permission==='granted'?'Notifications autorisées. Les rappels intelligents fonctionnent lorsque l’app est active; le service worker est prêt pour Web Push.':'Active les notifications pour recevoir les rappels du coach.'}
async function loadQuotes(force=false){if(!force&&data.quotes?.length){quotes=data.quotes;return}try{const r=await fetch('/api/quotes');if(!r.ok)throw new Error();const j=await r.json();if(j.quotes?.length){quotes=j.quotes;data.quotes=quotes;await DB.save(data);return}}catch{}quotes=[{text:'Success is the sum of small efforts, repeated day in and day out.',author:'Robert Collier'},{text:'The secret of getting ahead is getting started.',author:'Mark Twain'},{text:'You do not have to be extreme, just consistent.',author:'Unknown'}]}
function renderStoriesStrip(){const items=(quotes.length?quotes:data.quotes||[]).slice(0,7);$('#storiesStrip').innerHTML=items.map((q,i)=>`<button class="story-chip" data-story="${i}"><div class="story-ring"><div>${i+1}</div></div><small>${q.author||'Daily'}</small></button>`).join('')}
function renderStories(){if(!quotes.length)return;quoteIndex=(quoteIndex+quotes.length)%quotes.length;const q=quotes[quoteIndex];$('#quoteText').textContent=q.text;$('#quoteAuthor').textContent=`— ${q.author||'Unknown'}`;$('#storyProgress').innerHTML=quotes.slice(0,Math.min(8,quotes.length)).map((_,i)=>`<i class="${i===quoteIndex%Math.min(8,quotes.length)?'active':''}"></i>`).join('')}
function nav(view){currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));$('#pageTitle').textContent={today:'Aujourd’hui',workout:'Workout',progress:'Progress',stories:'Stories',settings:'Settings'}[view];if(view==='progress')requestAnimationFrame(renderProgress);if(view==='stories')renderStories();scrollTo({top:0,behavior:'smooth'})}
function openWeight(){modal(`<h3>Ajouter le poids</h3><div class="field"><label>Poids (kg)</label><input id="weightInput" type="number" step="0.1" inputmode="decimal"></div><button id="saveWeight" class="primary full" type="button">Enregistrer</button>`)}
function openSteps(){modal(`<h3>Pas aujourd’hui</h3><div class="field"><label>Nombre de pas</label><input id="stepsInput" type="number" inputmode="numeric" value="${day().steps||''}"></div><button id="saveSteps" class="primary full" type="button">Enregistrer</button>`)}
function openCheckin(){modal(`<h3>Check-in</h3><div class="field"><label>Faim 1–5</label><input id="hungerInput" type="number" min="1" max="5" value="${day().hunger||3}"></div><div class="field"><label>Énergie 1–5</label><input id="energyInput" type="number" min="1" max="5" value="${day().energy||3}"></div><button id="saveCheckin" class="primary full" type="button">Enregistrer</button>`)}
function openFood(){modal(`<h3>Ajouter nutrition</h3><div class="field"><label>Calories</label><input id="calInput" type="number" inputmode="numeric"></div><div class="field"><label>Protéines (g)</label><input id="protInput" type="number" inputmode="numeric"></div><button id="saveFood" class="primary full" type="button">Ajouter</button><hr><div class="field"><label>Recherche Open Food Facts</label><input id="offQuery" placeholder="ex: skyr, thon, poulet"></div><button id="offSearch" class="secondary full" type="button">Rechercher</button><div id="offResults"></div>`)}
function openWorkout(minimum=false){const plan=Engine.todaysPlan(data),base=Engine.plans[plan],list=minimum?[...base.filter(x=>x.type==='strength').slice(0,3),{id:'mini-cardio',name:plan==='A'?'Vélo':'Rameur',type:'cardio',minutes:5}]:base;modal(`<h3>${minimum?'⚡ Minimum workout':`Workout ${plan}`}</h3><p class="subtle">${minimum?'Compte pour la série, mais ne déclenche pas de progression de charge.':'Loggue charge, reps et RIR. La prochaine prescription sera calculée automatiquement.'}</p><div id="workoutForm">${list.map(ex=>{if(ex.type==='cardio')return `<div class="workout-ex" data-ex="${ex.id}" data-type="cardio"><div class="workout-ex-head"><b>${ex.name}</b><small>${minimum?5:Engine.cardioMinutes(data)} min</small></div></div>`;const p=Engine.prescription(data,ex),sets=minimum?1:p.sets;return `<div class="workout-ex" data-ex="${ex.id}" data-type="strength"><div class="workout-ex-head"><b>${ex.name}</b><small>${p.text}</small></div><div class="field"><label>Charge (kg)</label><input class="load" type="number" step="0.5" value="${p.load||''}"></div>${Array.from({length:sets},(_,i)=>`<div class="set-row"><span>Série ${i+1}</span><input class="reps" type="number" placeholder="reps" value="${ex.min}"><input class="rir" type="number" min="0" max="5" placeholder="RIR" value="3"></div>`).join('')}</div>`}).join('')}</div><button id="completeWorkout" data-minimum="${minimum?'1':'0'}" data-plan="${plan}" class="primary full" type="button">Terminer la séance</button>`)}
function collectWorkout(btn){const minimum=btn.dataset.minimum==='1',plan=btn.dataset.plan,exercises=$$('#workoutForm .workout-ex').map(el=>{if(el.dataset.type==='cardio')return {id:el.dataset.ex,type:'cardio',minutes:minimum?5:Engine.cardioMinutes(data)};return {id:el.dataset.ex,type:'strength',load:Number(el.querySelector('.load').value||0),sets:[...el.querySelectorAll('.set-row')].map(r=>({reps:Number(r.querySelector('.reps').value||0),rir:Number(r.querySelector('.rir').value||0)}))}});return {date:todayKey(),timestamp:new Date().toISOString(),plan,minimum,completed:true,exercises}}
function scheduleSmartReminders(){reminderTimers.forEach(clearTimeout);reminderTimers=[];if(!data.settings.notifications||!('Notification'in window)||Notification.permission!=='granted')return;const completed=data.workouts.some(w=>w.date===todayKey()&&w.completed);if(completed)return;const messages=[['18:00','Workout ready','Your session is ready. Start with one set.'],['19:30','Keep the streak','12 minutes are enough to protect your streak.'],['21:00','Minimum workout','Last option: 8 minutes and you are done.']];for(const [time,title,body] of messages){const [h,m]=time.split(':').map(Number),target=new Date();target.setHours(h,m,0,0);const delay=target-new Date();if(delay>0&&delay<86400000)reminderTimers.push(setTimeout(()=>navigator.serviceWorker?.ready.then(r=>r.showNotification(title,{body,icon:'/icon-192.svg',tag:`coach-${time}`})),delay))}}
function bind(){
  $$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
  document.addEventListener('click',async e=>{
    const action=e.target.closest('[data-action]')?.dataset.action;if(action==='weight')openWeight();if(action==='food')openFood();if(action==='steps')openSteps();if(action==='checkin')openCheckin();
    const story=e.target.closest('[data-story]');if(story){quoteIndex=Number(story.dataset.story);nav('stories')}
    if(e.target.id==='saveWeight'){const v=Number($('#weightInput').value);if(v>0){data.weights=data.weights.filter(x=>x.date!==todayKey());data.weights.push({date:todayKey(),value:v});await save();$('#modal').close()}}
    if(e.target.id==='saveSteps'){day().steps=Number($('#stepsInput').value||0);await save();$('#modal').close()}
    if(e.target.id==='saveCheckin'){day().hunger=Number($('#hungerInput').value);day().energy=Number($('#energyInput').value);await save();$('#modal').close()}
    if(e.target.id==='saveFood'){day().calories+=Number($('#calInput').value||0);day().protein+=Number($('#protInput').value||0);await save();$('#modal').close()}
    if(e.target.id==='offSearch'){const q=$('#offQuery').value.trim();if(!q)return;$('#offResults').textContent='Recherche…';try{const r=await fetch(`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&action=process&json=1&page_size=5`);const j=await r.json();$('#offResults').innerHTML=(j.products||[]).map(p=>`<div class="food-result"><b>${p.product_name||'Produit'}</b><div class="subtle">${p.nutriments?.['energy-kcal_100g']||'?'} kcal/100g • ${p.nutriments?.proteins_100g||'?'} g prot.</div></div>`).join('')||'Aucun résultat'}catch{$('#offResults').textContent='Recherche indisponible.'}}
    if(e.target.id==='completeWorkout'){data.workouts.push(collectWorkout(e.target));await save();$('#modal').close()}
  });
  $('#startWorkout').onclick=()=>openWorkout(false);$('#minimumWorkout').onclick=()=>openWorkout(true);
  $('#nextQuote').onclick=()=>{quoteIndex++;renderStories()};$('#prevQuote').onclick=()=>{quoteIndex--;renderStories()};
  $('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return alert('Notifications non supportées.');const p=await Notification.requestPermission();data.settings.notifications=p==='granted';await save()};
  $('#testNotify').onclick=async()=>{if(Notification.permission!=='granted')await Notification.requestPermission();if(Notification.permission==='granted'){const reg=await navigator.serviceWorker.ready;reg.showNotification('Autopilot Fit',{body:'Workout ready. One set is enough to start.',icon:'/icon-192.svg'})}};
  $('#saveSettings').onclick=async()=>{for(const [id,key] of [['calTarget','calTarget'],['proteinTarget','proteinTarget'],['stepsTargetInput','stepsTarget'],['minCalTarget','minCalTarget'],['loadIncrement','loadIncrement']])data.profile[key]=Number($('#'+id).value);data.profile.autopilotEnabled=$('#autopilotEnabled').checked;await save()};
  $('#exportJson').onclick=()=>download(`autopilot-fit-${todayKey()}.json`,new Blob([DB.export(data)],{type:'application/json'}));
  $('#exportCsv').onclick=()=>{const rows=['date,weight,steps,calories,protein,hunger,energy,workout,volume'];const dates=new Set([...data.weights.map(x=>x.date),...Object.keys(data.days),...data.workouts.map(x=>x.date)]);[...dates].sort().forEach(date=>{const w=data.weights.filter(x=>x.date===date).at(-1)?.value||'',d=data.days[date]||{},wo=data.workouts.filter(x=>x.date===date&&x.completed),vol=wo.reduce((s,x)=>s+Engine.volume(x),0);rows.push([date,w,d.steps||'',d.calories||'',d.protein||'',d.hunger||'',d.energy||'',wo.map(x=>x.minimum?'minimum':x.plan).join('|'),Math.round(vol)||''].join(','))});download(`autopilot-fit-${todayKey()}.csv`,new Blob([rows.join('\n')],{type:'text/csv'}))};
  $('#importJson').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const j=JSON.parse(await f.text());data=DB.merge(DB.clone(DB.defaults),j.data||j);await save();alert('Import terminé.')}catch{alert('Fichier invalide.')}};
  $('#deleteData').onclick=async()=>{if(confirm('Effacer toutes les données locales ?')){await DB.clear();data=DB.clone(DB.defaults);await save()}};
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
  window.addEventListener('resize',()=>currentView==='progress'&&renderProgress());
}
async function init(){if('serviceWorker'in navigator)await navigator.serviceWorker.register('/sw-v2.js');data=await DB.load();await loadQuotes();const applied=Engine.maybeApplyWeekly(data);if(applied?.eligible)await DB.save(data);bind();renderAll()}
init();
